tserd14browser-elasticsearch:
  container_name: tserd14browser-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/tserd14Browser/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
tserd14browser-mysql:
  container_name: tserd14browser-mysql
  image: mysql:5.7.9
  # volumes:
  #   - ~/volumes/jhipster/tserd14Browser/mysql/:/var/lib/mysql/
  environment:
    - MYSQL_USER=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=tserd14browser
  ports:
    - "3306:3306"
  command: mysqld --lower_case_table_names=1
